package write

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
)

// // // // // // // // // //

// GeneratedHeader marks files owned by this generator. Cleanup only touches files with this header.
const GeneratedHeader = "// Code generated by goopenapigen; DO NOT EDIT."

// //

// File writes atomically through temp + rename. Identical content is not rewritten.
func File(outputFile string, dataArr []byte, force bool) error {
	if outputFile == "" {
		return fmt.Errorf("output path is empty")
	}

	if existingData, err := os.ReadFile(outputFile); err == nil {
		if bytes.Equal(existingData, dataArr) {
			return nil
		}
	}

	outputDir := filepath.Dir(outputFile)
	if err := PrepareDir(outputDir, force); err != nil {
		return err
	}

	tempFile, err := os.CreateTemp(outputDir, ".goopenapigen-*")
	if err != nil {
		return fmt.Errorf("create temp file: %w", err)
	}

	tempPath := tempFile.Name()
	removeTempFlag := true

	defer func() {
		_ = tempFile.Close()
		if removeTempFlag {
			_ = os.Remove(tempPath)
		}
	}()

	if err = tempFile.Chmod(0644); err != nil {
		return fmt.Errorf("chmod temp file: %w", err)
	}

	if _, err = tempFile.Write(dataArr); err != nil {
		return fmt.Errorf("write temp file: %w", err)
	}

	if err = tempFile.Close(); err != nil {
		return fmt.Errorf("close temp file: %w", err)
	}

	if err = os.Rename(tempPath, outputFile); err != nil {
		return fmt.Errorf("replace output file: %w", err)
	}

	removeTempFlag = false
	return nil
}
