get:
  operationId: taskCommentsList
  summary: List task comments.
  tags: [ tasks, comments ]
  x-func: TaskCommentsList
  parameters:
    - $ref: parameters/task_id
    - $ref: '#/components/parameters/Limit'
    - $ref: '#/components/parameters/Offset'
  responses:
    '200':
      $ref: responses/comment_list
    default:
      $ref: '#/components/responses/Problem'
post:
  operationId: taskCommentsCreate
  summary: Add a comment to a task.
  tags: [ tasks, comments ]
  x-func: TaskCommentsCreate
  parameters:
    - $ref: parameters/task_id
  requestBody:
    $ref: components/requestBodies/comment_create
  responses:
    '201':
      description: Created comment.
      content:
        application/json:
          schema:
            $ref: schemas/comment
    default:
      $ref: '#/components/responses/Problem'
